=begin
#CryptoQuery API

#API for Senior Project

OpenAPI spec version: v1
Contact: fsolano@nevada.unr.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/article_post_dto'
require 'swagger_client/models/article_query_profile_post_dto'
require 'swagger_client/models/authenticate_post_dto'
require 'swagger_client/models/login_model'
require 'swagger_client/models/user_post_dto'

# APIs
require 'swagger_client/api/articles_api'
require 'swagger_client/api/authenticate_api'
require 'swagger_client/api/users_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
