=begin
#CryptoQuery API

#API for Senior Project

OpenAPI spec version: v1
Contact: fsolano@nevada.unr.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LoginModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LoginModel' do
  before do
    # run before each test
    @instance = SwaggerClient::LoginModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoginModel' do
    it 'should create an instance of LoginModel' do
      expect(@instance).to be_instance_of(SwaggerClient::LoginModel)
    end
  end
  describe 'test attribute "username"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "password"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

