/**
 * CryptoQuery API
 * API for Senior Project
 *
 * OpenAPI spec version: v1
 * Contact: fsolano@nevada.unr.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CryptoQueryApi) {
      root.CryptoQueryApi = {};
    }
    root.CryptoQueryApi.ArticlePostDto = factory(root.CryptoQueryApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ArticlePostDto model module.
   * @module model/ArticlePostDto
   * @version v1
   */

  /**
   * Constructs a new <code>ArticlePostDto</code>.
   * @alias module:model/ArticlePostDto
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>ArticlePostDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArticlePostDto} obj Optional instance to populate.
   * @return {module:model/ArticlePostDto} The populated <code>ArticlePostDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('dateOfPublification')) {
        obj['dateOfPublification'] = ApiClient.convertToType(data['dateOfPublification'], 'String');
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = ApiClient.convertToType(data['author'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('topic')) {
        obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
      }
      if (data.hasOwnProperty('complexity')) {
        obj['complexity'] = ApiClient.convertToType(data['complexity'], 'Number');
      }
      if (data.hasOwnProperty('quality')) {
        obj['quality'] = ApiClient.convertToType(data['quality'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;
  /**
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {String} dateOfPublification
   */
  exports.prototype['dateOfPublification'] = undefined;
  /**
   * @member {String} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} topic
   */
  exports.prototype['topic'] = undefined;
  /**
   * @member {Number} complexity
   */
  exports.prototype['complexity'] = undefined;
  /**
   * @member {Number} quality
   */
  exports.prototype['quality'] = undefined;



  return exports;
}));


