# coding: utf-8

"""
    CryptoQuery API

    API for Senior Project  # noqa: E501

    OpenAPI spec version: v1
    Contact: fsolano@nevada.unr.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authenticate_api import AuthenticateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthenticateApi(unittest.TestCase):
    """AuthenticateApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.authenticate_api.AuthenticateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_post(self):
        """Test case for authenticate_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
