# coding: utf-8

"""
    CryptoQuery API

    API for Senior Project  # noqa: E501

    OpenAPI spec version: v1
    Contact: fsolano@nevada.unr.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.articles_api import ArticlesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArticlesApi(unittest.TestCase):
    """ArticlesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.articles_api.ArticlesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_articles_by_id_delete(self):
        """Test case for articles_by_id_delete

        """
        pass

    def test_articles_by_id_get(self):
        """Test case for articles_by_id_get

        """
        pass

    def test_articles_get(self):
        """Test case for articles_get

          # noqa: E501
        """
        pass

    def test_articles_post(self):
        """Test case for articles_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
