# coding: utf-8

"""
    CryptoQuery API

    API for Senior Project  # noqa: E501

    OpenAPI spec version: v1
    Contact: fsolano@nevada.unr.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.article_post_dto import ArticlePostDto  # noqa: E501
from swagger_client.rest import ApiException


class TestArticlePostDto(unittest.TestCase):
    """ArticlePostDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArticlePostDto(self):
        """Test ArticlePostDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.article_post_dto.ArticlePostDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
