# coding: utf-8

# flake8: noqa
"""
    CryptoQuery API

    API for Senior Project  # noqa: E501

    OpenAPI spec version: v1
    Contact: fsolano@nevada.unr.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.article_post_dto import ArticlePostDto
from swagger_client.models.article_query_profile_post_dto import ArticleQueryProfilePostDto
from swagger_client.models.authenticate_post_dto import AuthenticatePostDto
from swagger_client.models.login_model import LoginModel
from swagger_client.models.user_post_dto import UserPostDto
