/**
 * CryptoQuery API
 * API for Senior Project
 *
 * OpenAPI spec version: v1
 * Contact: fsolano@nevada.unr.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CryptoQueryApi);
  }
}(this, function(expect, CryptoQueryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CryptoQueryApi.ArticlePostDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticlePostDto', function() {
    it('should create an instance of ArticlePostDto', function() {
      // uncomment below and update the code to test ArticlePostDto
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be.a(CryptoQueryApi.ArticlePostDto);
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property dateOfPublification (base name: "dateOfPublification")', function() {
      // uncomment below and update the code to test the property dateOfPublification
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property author (base name: "author")', function() {
      // uncomment below and update the code to test the property author
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property topic (base name: "topic")', function() {
      // uncomment below and update the code to test the property topic
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property complexity (base name: "complexity")', function() {
      // uncomment below and update the code to test the property complexity
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

    it('should have the property quality (base name: "quality")', function() {
      // uncomment below and update the code to test the property quality
      //var instane = new CryptoQueryApi.ArticlePostDto();
      //expect(instance).to.be();
    });

  });

}));
