/**
 * CryptoQuery API
 * API for Senior Project
 *
 * OpenAPI spec version: v1
 * Contact: fsolano@nevada.unr.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CryptoQueryApi);
  }
}(this, function(expect, CryptoQueryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CryptoQueryApi.ArticleQueryProfilePostDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticleQueryProfilePostDto', function() {
    it('should create an instance of ArticleQueryProfilePostDto', function() {
      // uncomment below and update the code to test ArticleQueryProfilePostDto
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be.a(CryptoQueryApi.ArticleQueryProfilePostDto);
    });

    it('should have the property topics (base name: "topics")', function() {
      // uncomment below and update the code to test the property topics
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be();
    });

    it('should have the property complexity (base name: "complexity")', function() {
      // uncomment below and update the code to test the property complexity
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be();
    });

    it('should have the property quality (base name: "quality")', function() {
      // uncomment below and update the code to test the property quality
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be();
    });

    it('should have the property pushToken (base name: "pushToken")', function() {
      // uncomment below and update the code to test the property pushToken
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be();
    });

    it('should have the property pushEnabled (base name: "pushEnabled")', function() {
      // uncomment below and update the code to test the property pushEnabled
      //var instane = new CryptoQueryApi.ArticleQueryProfilePostDto();
      //expect(instance).to.be();
    });

  });

}));
