=begin
#CryptoQuery API

#API for Senior Project

OpenAPI spec version: v1
Contact: fsolano@nevada.unr.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ArticlesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ArticlesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ArticlesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArticlesApi' do
    it 'should create an instance of ArticlesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ArticlesApi)
    end
  end

  # unit tests for articles_by_id_delete
  # 
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'articles_by_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for articles_by_id_get
  # 
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'articles_by_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for articles_get
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'articles_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for articles_post
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ArticlePostDto>] :article_post_dto_collection 
  # @return [nil]
  describe 'articles_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
