=begin
#CryptoQuery API

#API for Senior Project

OpenAPI spec version: v1
Contact: fsolano@nevada.unr.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuthenticateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthenticateApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthenticateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticateApi' do
    it 'should create an instance of AuthenticateApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthenticateApi)
    end
  end

  # unit tests for authenticate_post
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [LoginModel] :login 
  # @return [AuthenticatePostDto]
  describe 'authenticate_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
