=begin
#CryptoQuery API

#API for Senior Project

OpenAPI spec version: v1
Contact: fsolano@nevada.unr.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::UsersApi)
    end
  end

  # unit tests for users_by_id_delete
  # 
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_by_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_by_id_get
  # 
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_by_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_by_id_update_password_post
  # 
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :new_password 
  # @return [nil]
  describe 'users_by_id_update_password_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_get
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_post
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [UserPostDto] :user_post_dto 
  # @return [nil]
  describe 'users_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
